### ISSUE TITLE
Dark mode support based on Baseimage config

### ISSUE THREAD

**Issue by Uplinkpro** [laromicas/docker-romvault#2]
Was reading over The baseimage repo as I would like to Enable darkmode Most of it is setup already but it seems the dockerfile needs adjusting to support it as stated:

> The application's Dockerfile should install the Adwaita style/theme. It is provided by the adwaita-qt package, available from the Ubuntu, Debian or Alpine Linux software repositories.

As for romvault itself all you need to do is add darkmode to the config XML as stated on the website.

**Comment by shinji257** [comment]
~~This docker already has a DARK_MODE env option which will toggle it to dark mode.~~

~~Kinda funny because I use the unraid app that uses this docker container and it has a setting to install additional packages but it doesn't do anything.  XD~~

~~Installing the package manually I found that you also have to remove a leftover stat override due to an error regarding messagebus.  The group no longer exists in the image.  Once that it is fixed it doesn't fix the way dark mode looks.  It looks the same as if the package wasn't there which is that there is a white background for the buttons on the side as well as the various scroll boxes.~~

~~Enabling Darkness in the RomVault config (you have to do it there manually)~~

Figured it out.
Set DARK_MODE to 1
Edit RomVault3cfg.xml (it's in the /config folder) and add Darkness setting (https://wiki.romvault.com/doku.php?id=config_xml#darkness)
Add a graphics pack in the /config folder (wherever it is mounted to) (https://wiki.romvault.com/doku.php?id=graphics_packs)
I'm using Metro (Dark) by azazel_1125 for the graphics pack

This is what I ended up with.  Looks good.
![image](https://github.com/laromicas/docker-romvault/assets/261005/a986c1c1-d4b8-49e1-8546-6b150a6f9def)

**Comment by laromicas** [comment]
Thanks for your investigation, I will add it to the README.

**Comment by Uplinkpro** [comment]
Strange when I tried that I get this 
![image](https://github.com/laromicas/docker-romvault/assets/40792597/817b5764-0320-4245-90db-35768e02aca5)

I Should add that I'm not using the unraid template though as I get an error with permissions. Im using just a simple compose file `version: '3'
services:
  romvault:
    container_name: ROMvault
    image: laromicas/romvault
    ports:
      - "5800:5800"
    tty: true
    restart: always
    environment:
      - PUID:99
      - PGID:100
      - UMASK:000
      - DARK_MODE:1
    volumes:
      - /mnt/user/appdata/ROMVault:/config:rw
      - /mnt/user/appdata/ROMVault/DatRoot:/config/DatRoot:rw
      - /mnt/user/appdata/ROMVault/RomRoot:/config/RomRoot:rw
      - /mnt/user/appdata/ROMVault/ToSort:/config/ToSort:rw`

Edit : Added the graphics.zip to the base folder and the buttons all changed however the top car is still bright.

**Comment by laromicas** [comment]
It happened to me first time I ran it with dark mode, restarted and it worked. Ensure that `<Darkness>true</Darkness>` is in your xml config file.
![image](https://github.com/laromicas/docker-romvault/assets/2052864/330c735a-4c30-4a41-9c62-ef02f82f4646)

**Comment by Uplinkpro** [comment]
> It happened to me first time I ran it with dark mode, restarted and it worked. Ensure that `<Darkness>true</Darkness>` is in your xml config file. ![image](https://user-images.githubusercontent.com/2052864/284005865-330c735a-4c30-4a41-9c62-ef02f82f4646.png)

Yup did that , very strange.

**Comment by shinji257** [comment]
Make sure it is indented properly because it has to be right in the Settings scope.  Here is my file as an example.

Note my location for the Darkness option at the very bottom.  Maybe you are indenting more than 2 spaces for it?
https://gist.github.com/shinji257/bde2b36fbad255fc39eb267cc2425353

**Comment by Uplinkpro** [comment]
> Make sure it is indented properly because it has to be right in the Settings scope. Here is my file as an example.
> 
> Note my location for the Darkness option at the very bottom. Maybe you are indenting more than 2 spaces for it? https://gist.github.com/shinji257/bde2b36fbad255fc39eb267cc2425353

Copy and pasted it and still nothing. Just curious as well. Every time I restart the docker the registration thing starts up with it. Is that normal behavior? If not it might be an issue elsewhere.

**Comment by Uplinkpro** [comment]
So somehow after giving the RV unraid docker admin privileges it works and the darkmode fix works too
